version: "3"
services:
  hadoop-master:
    image: localhost:5000/hadoop
    command: ~/start-hadoop.sh
    ports:
      - "50070:50070"
      - "8088:8088"
    volumes:
      ./hadoop-slaves:/usr/local/hadoop/etc/hadoop/slaves
    environment:
      yarn.resourcemanager.hostname: hadoop-master
      fs.defaultFS: hdfs://hadoop-master:9000
  hadoop-slave:
    image: 10.176.225.202:5000/hadoop
    command: ~/start-hadoop.sh
    volumes:
      ./hadoop-slaves:/usr/local/hadoop/etc/hadoop/slaves
    environment:
      yarn.resourcemanager.hostname: hadoop-master
      fs.defaultFS: hdfs://hadoop-master:9000
    deploy:
      replicas: 4
  registry:
    image: registry
    ports:
      - 5000:5000
    networks:
      - spark-network
    volumes:
      - "./registry/data_volume:/var/lib/registry"
      - "./registry:/data"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  master:
    image: localhost:5000/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
    expose:
      - "7077"
    networks:
      - spark-network
    deploy:
        replicas: 1
        placement:
          constraints: [node.role == manager]
    environment:
        SPARK_LOCAL_IP: 0.0.0.0
  worker:
    image: 10.176.225.202:5000/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    networks:
      - spark-network
    deploy:
      replicas: 4
      placement:
            constraints: [node.role != manager]
  notebook:
    image: jupyter/pyspark-notebook
    command: start-notebook.sh --NotebookApp.token='' --ip=0.0.0.0
    ports:
      - "8888:8888"
    networks:
      - spark-network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  proxy:
    image: spark-ui-proxy
    command: master:8080 80
    ports:
      - "80:80"
    networks:
      - spark-network
    deploy:
      replicas: 1
      placement:
          constraints: [node.role == manager]
networks:
  spark-network:
    driver: overlay
