version: "3"
services:
  registry:
    image: registry
    ports:
      - "5000:5000"
      - "443:5000"
    networks:
      - spark-network
    volumes:
      - "./registry/data_volume:/var/lib/registry"
      - "./registry/letsencrypt_cache:/data/letsencrypt"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE: /data/letsencrypt
      REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL: pratheek.rebala@time.com 
  master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
    expose:
      - "7077"
    networks:
      - spark-network
    deploy:
        replicas: 1
        placement:
          constraints: [node.role == manager]
    environment:
        SPARK_LOCAL_IP: 0.0.0.0
  worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    networks:
      - spark-network
    deploy:
      replicas: 2
      placement:
            constraints: [node.role != manager]
  notebook:
    image: jupyter/pyspark-notebook
    command: start-notebook.sh --NotebookApp.token='' --ip=0.0.0.0
    ports:
      - "8888:8888"
    networks:
      - spark-network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  proxy:
    image: spark-ui-proxy
    command: master:8080 80
    ports:
      - "80:80"
    networks:
      - spark-network
    deploy:
      replicas: 1
      placement:
          constraints: [node.role == manager]
networks:
  spark-network:
    driver: overlay
